### ISSUE TITLE
Setup do banco de dados

### ISSUE THREAD

**Issue by hdind** [SouJunior/Ilimidados-Dashboards#16]
Precisamos fazer o setup do banco de dados! Para isso precisamos:

- Buscar as credenciais com os responsáveis (Pedro Fogaça)
- Tentar conectar ao banco usando as credenciais passadas
- Observer se já existe alguma coisa no banco
- Testar o envio e extração de dados de teste do banco

Para conectar ao banco recomendo o uso de ferramentas como o Dbeaver (essa já usei, achei bem fácil de mexer) ou DBVisualizer (essa nunca usei, mas fica a seu critério) - https://www.tabnews.com.br/raf/quais-as-melhores-ferramentas-ou-ide-gratuitas-para-banco-de-dados

**Comment by Patqueirozf** [comment]
Tarefa concluída. O banco de dados está ativo, estabeleci conexão com ele, as credenciais estão corretas, verifiquei a existência de dados preexistentes, fiz testes de integração, enviei e extrai dados de forma tranquila, o banco está nos conformes.

**Comment by camitimm** [comment]
Conforme combinado na agenda de 30/09, Pedro Head afirmou que a tarefa está pronta.
