### ISSUE TITLE
Listar arquivos-tabelas que realmente vão para o banco de dados do LinkedIn

### ISSUE THREAD

**Issue by hdind** [SouJunior/Ilimidados-Dashboards#20]

**Comment by Moscarde** [comment]
Tabelas (RAW) utilizadas no atualmente no dashboard:
Página 1:
- Seguidores - Novos seguidores

**Comment by Moscarde** [comment]
Tabelas (RAW) utilizadas no atualmente no dashboard:

Página 1:

- Seguidores - Novos seguidores
- Conteúdo - Métricas
- Visitantes - Métricas visitantes

Página 2:

- Seguidores - Nível de experiência
- Visitantes - Nível de experiência
- Visitantes - Função
- Visitantes - Tamanho da empresa

Página 3:

- Conteúdo - Todas as publicações
- Conteúdo - Métricas
- Concorrentes - Concorrentes

**Comment by Moscarde** [comment]
Nota:
As colunas listadas nessa task são as que foram necessárias para a construção das primeiras versões do dashboard do Linkedin, porém não descarta a utilização das demais colunas para melhorias ou novos componentes.
